### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by andresv** [xmikos/qspectrumanalyzer#1]
Hi,

I am trying to build it under Ubuntu 14.10. It is quite a pain to meet all the python3 dependencies without knowing exactly what is needed and how they should be installed.

It would be a good reference for other platforms as well if for example there is proper install instructions for Ubuntu.

**Comment by andresv** [comment]
https://github.com/xmikos/qspectrumanalyzer/pull/2

**Comment by xmikos** [comment]
Hello,

please look at my comment under your pull request. I can add install instructions for Ubuntu into README, but I would prefer if someone can create proper Debian/Ubuntu source package (`control` file or what Debian/Ubuntu uses).

**Comment by xmikos** [comment]
I have added installation instructions to README.rst, this can be closed.
