### ISSUE TITLE
Switch to PyQt 5

### ISSUE THREAD

**Issue by xmikos** [xmikos/qspectrumanalyzer#12]
PyQtGraph should support PyQt 5 from version 0.10.0 onward. Switch QSpectrumAnalyzer to PyQt 5, but possibly still support PyQt 4 (or PySide) by use of [QtPy](https://github.com/spyder-ide/qtpy) or [Qt.py](https://github.com/mottosso/Qt.py) wrapper.

**Comment by bogdanr** [comment]
This would solve dependencies issues on some distros. Looking forward to this one.

**Comment by xmikos** [comment]
Done in Git master branch. I am using Qt.py wrapper, so now it should work with both PyQt4, PyQt5, PySide and PySide2. I have tested it only with PyQt4 and PyQt5, which seems to work without problems (if you have both bindings installed, PyQt5 is chosen by default).
