### ISSUE TITLE
Fix for ppm and crop% for hackrf

### ISSUE THREAD

**Issue by securisec** [xmikos/qspectrumanalyzer#16]
Hi, is there a fix for the ppm and crop% for the hackrf? Cant change those and the output of a hackrf_sweep is this..

![image](https://cloud.githubusercontent.com/assets/22226823/23165104/74a43b90-f808-11e6-86ba-589b4f592abe.png)

Thanks!

**Comment by xmikos** [comment]
`hackrf_sweep` backend has been developed by @miek and @mossmann. According to my understanding hackrf_sweep tool enables wideband spectrum monitoring by rapidly retuning the radio without requiring individual tuning requests from the host computer. So I think crop must be implemented directly in hackrf_sweep tool to work as expected.

Same applies to ppm correction, hackrf_sweep tool will need to add support for it.

But maybe I am mistaken. It could be possibly hacked upon it, but I don't think that is good solution.
