### ISSUE TITLE
HackRF Sample Rate

### ISSUE THREAD

**Issue by derekchal** [xmikos/qspectrumanalyzer#18]
I am unable to change the sample rate when using a hackrf.
Does this come into the same category as the ppm and crop issues?

( On my Intel i7 notebook the 20million sample rate is ok, but on an older desktop machine that sample rate cannot be supported)

Other than that, a great tool for a fast scan of a large frequency space.

**Comment by xmikos** [comment]
Yes, definitely.

If you don't need extremely wide fast spectrum scan, you will be able to use my new universal [soapy_power](https://github.com/xmikos/soapy_power) backend soon. But it is not ready yet. I will release new stable version of QSpectrumAnalyzer when it is finished.

**Comment by xmikos** [comment]
New version with soapy_power backend has been released, I am closing it for now.
