### ISSUE TITLE
Can't see HackRF device on Ubuntu, all latest installed

### ISSUE THREAD

**Issue by kevmiyashiro** [xmikos/qspectrumanalyzer#19]
Hello,

We updated the firmware on the Hackrf to 2017.02.1, upgraded the CPLD, made sure the host software was updated including the hackrf_sweep.  We're on Ubuntu 14.04.

We can successfully see the hackrf with the hackrf_info command, and can run simple tasks with the GRC.

We can execute qspectrumanalyzer, but we cannot see hackrf_sweep as an option for backend, and when we click "start," we get an error at the command line stating:

"...
No supporting devices found"

Any suggestions?

**Comment by xmikos** [comment]
If you cannot see hackrf_sweep as an option, you are running old version of QSpectrumAnalyzer. Support for hackrf_sweep has been only in Git master branch and now is in latest version 1.5.0.
