### ISSUE TITLE
Gain sliders for hackrf

### ISSUE THREAD

**Issue by vsboost** [xmikos/qspectrumanalyzer#29]
Hi there,

Are you able to include
Slider for IF LNA gain 0-40db in 8db steps
Slider for Baseband VGA gain 0-62db in 2db steps
Button for RF amp 0db = OFF or 14db = ON

Cheers

**Comment by xmikos** [comment]
Hello,

you can set gain to -1 in GUI (displayed as "auto") and then add `--specific-gains` option to additional backend parameters in *Settings*. E.g.: `--specific-gains LNA=28,VGA=12,AMP=0`.

This is for `soapy_power` backend. For `hackrf_sweep` backend you can use options `-l` (LNA) and `-g` (VGA), but I am afraid this would not work (hackrf_sweep backend always sets gain be itself, even if you set it to -1.

**Comment by xmikos** [comment]
I will change hackrf_sweep backend to also work like soapy_power backend and let you know here.

**Comment by xmikos** [comment]
It's implemented in latest two commits (git master branch), please try it out and let me know how it works for you.

**Comment by vsboost** [comment]
Thanks for this.
