### ISSUE TITLE
Way to specify LNB LO frequency

### ISSUE THREAD

**Issue by sh123** [xmikos/qspectrumanalyzer#5]
First of all, thank you for this useful software.

Very often I'm using qspectrumanalyzer to make various measurements on HF, for example, filters, by using noise source and RTL-SDR dongle connected through HF up converter. 

It would be really nice if there will be a way to specify LNB LO up converter frequency (like in GQRX), so all frequencies in qspectrumanalyzer will be shown shifted to the "HF domain".

**Comment by xmikos** [comment]
Hi, this is finally done in last commit. Use negative LNB LO frequency for upconverters or positive LNB LO frequency for downconverters. Also I recommend using it with new *soapy_power* backend (it should also work with rtl_power / rtl_power_fftw / hackrf_sweep backends, but I didn't tested it so thoroughly with them).
