### ISSUE TITLE
No "File" and "Help" menu on top

### ISSUE THREAD

**Issue by stevevaius77** [xmikos/qspectrumanalyzer#8]
![image](https://cloud.githubusercontent.com/assets/24809488/22900057/ab84d256-f235-11e6-8de5-dc43f9030a9f.png)
There is no file and help menu on top to change device. And on Terminal again no supported device. What should be done to get Hackrf One to work with it? (Firmware 2017.02.1)
![image](https://cloud.githubusercontent.com/assets/24809488/22900104/e1a40fe6-f235-11e6-94c8-74261e672572.png)

**Comment by xmikos** [comment]
Sorry, I couldn't reproduce this issue. Isn't Ubuntu somehow messing with top menus of Qt 4 applications?

**Comment by Montilien** [comment]
Hi,
I have exactly the same issue...hackrf_info and hackrf_sweep checked works fine...
André

**Comment by xmikos** [comment]
Do you also use Ubuntu? I didn't have time to test in on latest Ubuntu yet, but will try...

**Comment by stevevaius77** [comment]
I solved it by reinstalling Ubuntu freshly and installing first all hackrf.git and reflashing firmware of my hackrf to be sure. I used this git https://github.com/miek/qspectrumanalyzer and install it not by system wide, but locally (pip3 install --user qspectrumanalyzer) which is now works smoothly

**Comment by Montilien** [comment]
Ho,
Yes i have a fresh Ubuntu upgrade to 16.04 release.
Regards

Envoyé de mon iPhone

Le 21 févr. 2017 à 13:05, Michal Krenek (Mikos) <notifications@github.com<mailto:notifications@github.com>> a écrit :


Do you also use Ubuntu? I didn't have time to test in on latest Ubuntu yet, but will try...

**Comment by Montilien** [comment]
Congratulations...you are the best...
I have changed the system settings And all works fine...
Thanks you vert much
André

Envoyé de mon iPhone

Le 21 févr. 2017 à 16:21, Michal Krenek (Mikos) <notifications@github.com<mailto:notifications@github.com>> a écrit :


According to my findings, there is option in Ubuntu: Settings / Appearance / Behavior. Check the options for show the menu in the window's title bar and for always show menus.

Try it and let me know (I didn't tested it, this is what I have found on Google).

**Comment by xmikos** [comment]
I have now tried it in Ubuntu 16.10 (in VirtualBox) and you don't have to change the settings. Menu is actually there, it is just pulled out of QSpectrumAnalyzer window and shown in the left side of the main Ubuntu to top bar (after you move mouse pointer there). I guess this is standard behavior of all windows in Ubuntu Desktop. See attached screenshot:

![qspectrumanalyzer_ubuntu](https://cloud.githubusercontent.com/assets/3603985/23231123/e869c09c-f946-11e6-9bf2-a8e0daa123e5.png)
