### ISSUE TITLE
Ubuntu 20.04: Unable to locate package soapysdr

### ISSUE THREAD

**Issue by OZ1SEJ** [xmikos/qspectrumanalyzer#97]
I can't seem to install soapysdr as per your instructions:

    $ sudo apt-get install soapysdr
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    E: Unable to locate package soapysdr

**Comment by Foxiks** [comment]
try it: sudo apt update && sudo apt install soapysdr-tools
